#!/usr/bin/python

# Eliminates duplicate entries from CSV files generated by BPWatch
#
# https://play.google.com/store/apps/details?id=com.boxeelab.healthlete.bpwatch
#
# Usage: < file.csv eliminate.py > new_file.csv

import csv
import sys

# readings are unique readings -- same sys/dias/pulse/date.
# if you had two identical readings on the same date, sorry, they're
# eliminated by this algorithm. The app sometimes writes slightly different
# times for duplicate readings, so the heuristic is to ignore time for
# purposes of determining duplication.
readings = {}

# entries are log entries where we append unique readings
entries = []

reader_obj = csv.reader(sys.stdin)
for row in reader_obj:
    key = (row[0], row[1], row[2], row[3])
    if readings.has_key(key):
        continue
    readings[key] = True
    entries.append(row)

writer_obj = csv.writer(sys.stdout)
for row in entries:
    writer_obj.writerow(row)
